---
- name: Check MOTD banner
  hosts: cat8k
  gather_facts: false

  tasks:
    - name: Show configured banners
      cisco.ios.ios_command:
        commands:
          - show running-config | include banner
      register: output

    - name: Display banner configuration
      ansible.builtin.debug:
        var: output.stdout_lines