---
- name: Get information from Cisco IOS XE
  hosts: cat8k
  gather_facts: false

  tasks:
    - name: Run show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: output

    - name: Display output
      ansible.builtin.debug:
        var: output.stdout_lines